### ISSUE TITLE
Multiple classes

### ISSUE THREAD

**Issue by extsoft** [OlenaKh/Training#1]
There are two training in the different room. The first trainer teaches how to use git. The second one demonstrates how to bake a cake. Second room can have only 6 people at the same time while the first one is unlimited. 

Some implementation details: 
- `learn` and `teach` methods has to accept a `subject` as an argument
- If there is no space in the room, proper message is displayed when a room tries to accept the new student.  We don’t learn a student if it is not in the room.

**Comment by OlenaKh** [comment]
Pull request is created for task #1. Hope it's not so bad...
@extsoft please check
p.s. I remember that I shouldn't push changes for more that 2-3 files... But I want to move to the next task :)
