### ISSUE TITLE
Add some unit tests

### ISSUE THREAD

**Issue by extsoft** [OlenaKh/Training#6]
Please create unit tests for all classes which **implement** an interface. You need only to test **methods which return a value**. Don't create tests for any other methods.

Please refer to the following pull request as for an example: https://github.com/extsoft/jwtabc-2018/pull/2/files

**Comment by OlenaKh** [comment]
Added 2 unit tests for JavaTeacher class. 
@extsoft Please review my PR. Is it Ok such solution for unit tests? (I've googled a bit to find help how to test System.out.println)

Later I will practice with other classes

p.s. Ooops... it's not PR... something went wrong.... :(
